# LIBRERIAS

In [4]:
import pandas as pd

# ANALISIS TABLA PRODUCTOS

In [8]:
# CARGA DE DATOS
Producto_Raw = pd.read_csv("../../Data/Raw/productos.csv")
Producto_Raw.head(20)

    id_producto         nombre_producto     categoria precio_base
0             1           Laptop Pro 14   Electrónica       $1200
1             2       Mouse Inalámbrico          Elec          35
2             3        Teclado Mecánico  electtronica          89
3             4             Monitor 24"   Electrónica         180
4             5     Audífonos Bluetooth   Electronica         $75
5             6          Cargador USB-C    Eletrónica         -25
6             7            Smartphone X   Electrónica         799
7             8              Tablet 10"   Electrónica        $250
8             9  Impresora Multifunción       Oficina         220
9            10        Silla Ergonómica       Muebles         310
10           11    Escritorio Ajustable       Muebles        $450
11           12           Router WiFi 6         Redes         140
12           13           Disco SSD 1TB   Electrónica         $95
13           14               Webcam HD    eletronica          60
14           15        Altavoz Portátil   Electrónica         $55
15           16     Cámara de Seguridad     Seguridad         210
16           17                 Hub USB       Oficina          28
17           18         Fuente de Poder   Electrónica        -110
18           19          Pendrive 128GB   ElecTrónica         $18
19           20        Aspiradora Robot         Hogar         650

In [ ]:
# NOS DA LA CANTIDAD DE FILAS, CANTIDAD DE COLUMNA, TIPO DE DATO POR COLUMNA Y NULL
Producto_Raw.info()

In [21]:
# CANTIDAD DE NULL POR COLUMNA
Producto_Raw.isnull().sum()

id_producto        0
nombre_producto    0
categoria          0
precio_base        0
dtype: int64

In [9]:
# CANTIDAD DE FILAS REPETIDAS
Producto_filas_cantidad = Producto_Raw.copy()

Producto_filas_cantidad['nombre_producto'] = Producto_filas_cantidad['nombre_producto'].str.strip()

Producto_filas_cantidad['categoria'] = Producto_filas_cantidad['categoria'].str.strip()

Producto_filas_cantidad.duplicated().sum()

np.int64(0)

In [10]:
# TE MUESTRA LOS DUPLICADOS EXACTOS POR FILAS
Producto_filas_cantidad = Producto_Raw.copy()

Producto_filas_cantidad['nombre_producto'] = Producto_filas_cantidad['nombre_producto'].str.strip()

Producto_filas_cantidad['categoria'] = Producto_filas_cantidad['categoria'].str.strip()

Producto_filas_cantidad[Producto_filas_cantidad.duplicated()]

Empty DataFrame
Columns: [id_producto, nombre_producto, categoria, precio_base]
Index: []

In [6]:
# CANTIDA DE DUPLICADOS EXCATOS POR ID
Producto_Raw.duplicated(subset='id_producto').sum()

np.int64(0)

In [8]:
# TE MUESTRA QUE ID SE REPITIO Y SU CANTIDAD
Conteo_id = Producto_Raw['id_producto'].value_counts()
Conteo_id[Conteo_id > 1]

Series([], Name: count, dtype: int64)

In [9]:
# SABER LA CANTIDAD DE NEGATIVOS QUE TIENES EN TU COLUMNA
(
    pd.to_numeric( # LO VUELBE NUMERO TEMPORALMENTE
        Producto_Raw['precio_base'].str.replace('$',''),
        errors='coerce' # SI ALGO FALLA LE PONE NULL
    ) < 0
).sum()

np.int64(2)

In [10]:
# SABER LOS ERRORES ORTOGRAFICO DE COLUMNA CATEGORIA
print(Producto_Raw['categoria'].value_counts())

categoria
Electrónica     7
Oficina         2
Muebles         2
Elec            1
electtronica    1
Electronica     1
Eletrónica      1
Redes           1
eletronica      1
Seguridad       1
ElecTrónica     1
Hogar           1
Name: count, dtype: int64

In [34]:

#SABER LOS ERRORES ORTOGRAFICO DE COLUMNA NOMBRE_PRODUCTO
print(Producto_Raw['nombre_producto'].value_counts())

nombre_producto
Laptop Pro 14             1
Mouse Inalámbrico         1
Teclado Mecánico          1
Monitor 24"               1
Audífonos Bluetooth       1
Cargador USB-C            1
Smartphone X              1
Tablet 10"                1
Impresora Multifunción    1
Silla Ergonómica          1
Escritorio Ajustable      1
Router WiFi 6             1
Disco SSD 1TB             1
Webcam HD                 1
Altavoz Portátil          1
Cámara de Seguridad       1
Hub USB                   1
Fuente de Poder           1
Pendrive 128GB            1
Aspiradora Robot          1
Name: count, dtype: int64

## ANALISIS TABLA PEDIDOS

In [13]:
Pedidos_Raw = pd.read_csv("../../Data/Raw/pedidos.csv")
Pedidos_Raw.head(20)

    id_pedido  id_producto id_cliente fecha_pedido  cantidad
0           1            4      C0002   2025-01-05         3
1           2            8      C0015   14/01/2025         2
2           3            4      C0035   01-23-2025         1
3           4           19      C0028   2025-02-01         1
4           5            1      C0006   10/02/2025         2
5           6            8      C0033   02-19-2025         8
6           7            1      C0036   2025-02-28         2
7           8           18      C0027   09/03/2025         2
8           9           15      C0038   03-18-2025         3
9          10            1      C0011   2025-03-27         5
10         11           99      C0018   05/04/2025         2
11         12            7      C0022   04-14-2025         1
12         13            3      C0025   2025-04-23         1
13         14           12      C0023   02/05/2025         8
14         15            9      C0003   05-11-2025         6
15         16           18      C0008   2025-05-20         5
16         17            3      C0036   29/05/2025         3
17         18           20      C0024   06-07-2025         8
18         19            7      C0005   2025-06-16         1
19         20            8      C0019   25/06/2025         1

In [14]:
Pedidos_Raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_pedido     88 non-null     int64
 1   id_producto   88 non-null     int64
 2   id_cliente    88 non-null     str
 3   fecha_pedido  88 non-null     str
 4   cantidad      88 non-null     int64
dtypes: int64(3), str(2)
memory usage: 3.6 KB

In [15]:
Pedidos_Raw.isnull().sum()

id_pedido       0
id_producto     0
id_cliente      0
fecha_pedido    0
cantidad        0
dtype: int64

In [16]:
# CANTIDAD DE DUPLICADOS POR FILA 
Pedido_cantidad_repetida = Pedidos_Raw.copy()
Pedido_cantidad_repetida['fecha_pedido'] = Pedido_cantidad_repetida['fecha_pedido'].str.strip()
Pedido_cantidad_repetida.duplicated().sum()

np.int64(8)

In [ ]:
# ME MUESTRA LA FILAS QUE SE REPITEN
Pedido_cantidad_repetida = Pedidos_Raw.copy()
Pedido_cantidad_repetida['fecha_pedido'] = Pedido_cantidad_repetida['fecha_pedido'].str.strip()
Pedido_cantidad_repetida[Pedido_cantidad_repetida.duplicated()]

    id_pedido  id_producto id_cliente fecha_pedido  cantidad
80          5            1      C0006   10/02/2025         2
81         12            7      C0022   04-14-2025         1
82         20            8      C0019   25/06/2025         1
83         27            6      C0030   08-27-2025         5
84         35            5      C0016   07/11/2025         7
85         42            3      C0025   01-09-2026         5
86         55           12      C0020   2026-05-06         2
87         68            8      C0001   31/08/2026         1

In [15]:
# CANTIDAD DE DUPLICADOS POR ID
print(Pedidos_Raw.duplicated(subset='id_pedido').sum())

8

In [ ]:
# ME DA LOS ID QUE SE REPITEN Y SU CANTIDAD QEU SE REPITE
conteo_ids = Pedidos_Raw['id_pedido'].value_counts()
conteo_ids[conteo_ids > 1]

id_pedido
5     2
12    2
20    2
27    2
35    2
42    2
55    2
68    2
Name: count, dtype: int64

In [ ]:
# SI TENGO NEGATIVOS EN CANTIDAD
(Pedidos_Raw['cantidad'] < 0).sum()

np.int64(0)

In [49]:
Pedidos_Raw[Pedidos_Raw['cantidad'] < 0]

Empty DataFrame
Columns: [id_pedido, id_producto, id_cliente, fecha_pedido, cantidad]
Index: []

In [16]:
Pedidos_Raw['fecha_pedido'].head(20)

0     2025-01-05
1     14/01/2025
2     01-23-2025
3     2025-02-01
4     10/02/2025
5     02-19-2025
6     2025-02-28
7     09/03/2025
8     03-18-2025
9     2025-03-27
10    05/04/2025
11    04-14-2025
12    2025-04-23
13    02/05/2025
14    05-11-2025
15    2025-05-20
16    29/05/2025
17    06-07-2025
18    2025-06-16
19    25/06/2025
Name: fecha_pedido, dtype: str

In [25]:
# ¿Todos los id_producto de Pedidos existen en Productos?
id_invalidos = ~Pedidos_Raw['id_producto'].isin(Producto_Raw['id_producto'])
Pedidos_Raw[id_invalidos]

    id_pedido  id_producto id_cliente fecha_pedido  cantidad
10         11           99      C0018   05/04/2025         2
21         22          100      C0030   2025-07-13        10
32         33          777      C0032   10-20-2025         5
43         44           99      C0036   27/01/2026         1

## ANALISIS TABLA AlMACENES

In [18]:
# CONECTAR DATOS Y MOSTRAR
Almacenes_Raw = pd.read_csv('../Data/Raw/almacenes.csv')
Almacenes_Raw.head(20)

   id_almacen ubicacion  capacidad
0           1      Lima      12000
1           2  Arequipa       8500
2           3  Trujillo       7000
3           4     cuzco       5000
4           5     Piura       6000
5           5    Piura        6000

In [19]:
# VER CANTIDAD DE FILA, COLUMNA Y TIPO DE DATOS QUE ES CADA COLUMNA
Almacenes_Raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_almacen  6 non-null      int64
 1   ubicacion   6 non-null      str
 2   capacidad   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [ ]:
# CANTIDAD DE NULL POR COLUMNA
Almacenes_Raw.isnull().sum()

id_almacen    0
ubicacion     0
capacidad     0
dtype: int64

In [ ]:
# MUESTRA LA CANTIDAD DE FILAS REPETIDAS
Almacenes_Temporal = Almacenes_Raw.copy()

Almacenes_Temporal['ubicacion'] = Almacenes_Temporal['ubicacion'].str.strip()

Almacenes_Temporal.duplicated().sum()

np.int64(1)

In [40]:
# MUESTRA LA FILA REPETIDA
Almacenes_Temporal = Almacenes_Raw.copy()

Almacenes_Temporal['ubicacion'] = Almacenes_Temporal['ubicacion'].str.strip()

Almacenes_Temporal[Almacenes_Temporal.duplicated()]

   id_almacen ubicacion  capacidad
5           5     Piura       6000

In [41]:
# MUESTRA LA CANTIDAD DE ID REPETIDAS
print(Almacenes_Raw.duplicated(subset='id_almacen').sum())

1

In [46]:
# MUESTRA SOLO LOS ID REPETIDOS Y LA CANTIDAD REPETIDA
Conteo_id = Almacenes_Raw['id_almacen'].value_counts()

Conteo_id[Conteo_id > 1]

id_almacen
5    2
Name: count, dtype: int64

In [48]:
# SABER LA CANTIDAD DE NEGATIVOS QUE TIENES EN TU COLUMNA
(Almacenes_Raw['capacidad'] < 0).sum()

np.int64(0)

In [ ]:
# ME MUESTRA QUE FILA TIENE EL NEGATIVO EN CAPACIDAD
Almacenes_Raw[Almacenes_Raw['capacidad'] < 0]

Empty DataFrame
Columns: [id_almacen, ubicacion, capacidad]
Index: []

In [30]:
# ¿Todos los id_almacen de Logistica existen en Almacenes?
id_invalidos = ~Logistica_Raw['id_almacen'].isin(Almacenes_Raw['id_almacen']) 
Logistica_Raw[id_invalidos]

Empty DataFrame
Columns: [id_pedido, id_almacen, fecha_entrega_real, estado_envio, costo_envio]
Index: []

# ANALISIS TABLA LOGISTICA

In [28]:
# CONECTAR Y MOSTRAR DATOS
Logistica_Raw = pd.read_csv('../Data/Raw/logistica.csv')

Logistica_Raw.head(20)

    id_pedido  id_almacen fecha_entrega_real estado_envio  costo_envio
0           1           5                NaN  En tránsito           22
1           2           1         22/01/2025  En tránsito           12
2           3           1         04/02/2025    Retrasado           18
3           4           4                NaN    Cancelado           18
4           5           3                NaN    Cancelado           28
5           6           5         2025-02-27    Entregado           18
6           7           1                NaN    Pendiente        10000
7           8           5         19/03/2025  En tránsito           12
8           9           2         2025-03-20    Entregado           20
9          10           5         2025-04-06    Entregado           12
10         11           5                NaN    Pendiente           22
11         12           2         2025-04-17    Entregado           22
12         13           1         2025-05-03    Entregado           15
13         14           3         2025-05-08    Entregado           15
14         15           2                NaN  En tránsito           22
15         16           5         2025-05-29    Entregado           22
16         17           2         2025-05-31    Entregado           30
17         18           2         2025-07-10    Entregado           22
18         19           1         2025-06-23    Entregado        10000
19         20           3         2025-07-06    Entregado           22

In [27]:
# NOS DA LA CANTIDAD DE FILAS, COLUMNAS Y SU TIPO DE DATOS DE CADA COLUMNA
Logistica_Raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_pedido           88 non-null     int64
 1   id_almacen          88 non-null     int64
 2   fecha_entrega_real  63 non-null     str
 3   estado_envio        88 non-null     str
 4   costo_envio         88 non-null     int64
dtypes: int64(3), str(2)
memory usage: 3.6 KB

In [13]:
# NOS DICE LA CANTIDAD DE NULL POR COLUMNA
Logistica_Raw.isnull().sum()

id_pedido              0
id_almacen             0
fecha_entrega_real    25
estado_envio           0
costo_envio            0
dtype: int64

In [53]:
# NOS DA LA CANTIDAD DE ID REPETIDOS
print(Logistica_Raw.duplicated(subset='id_pedido').sum())

8

In [54]:
# NOS DA LA ID REPETIDA Y SU CANTIDAD DE VECES 
Conteo_id_logistica = Logistica_Raw['id_pedido'].value_counts()

Conteo_id_logistica[Conteo_id_logistica > 1]

id_pedido
5     2
12    2
20    2
27    2
35    2
42    2
55    2
68    2
Name: count, dtype: int64

In [22]:
# TE MUESTRA LA FILAS REPETIDA
Logistica_filas_cantidad = Logistica_Raw.copy()

Logistica_filas_cantidad['fecha_entrega_real'] = Logistica_filas_cantidad['fecha_entrega_real'].str.strip()

Logistica_filas_cantidad['estado_envio'] = Logistica_filas_cantidad['estado_envio'].str.strip()

Logistica_filas_cantidad[Logistica_filas_cantidad.duplicated()]

Empty DataFrame
Columns: [id_pedido, id_almacen, fecha_entrega_real, estado_envio, costo_envio]
Index: []

In [23]:
# MUESTRA LA CANTIDAD DE FILAS REPETIDAS
Logistica_filas_cantidad = Logistica_Raw.copy()

Logistica_filas_cantidad['fecha_entrega_real'] = Logistica_filas_cantidad['fecha_entrega_real'].str.strip()

Logistica_filas_cantidad['estado_envio'] = Logistica_filas_cantidad['estado_envio'].str.strip()

Logistica_filas_cantidad.duplicated().sum()

np.int64(0)

In [57]:
# SABER SI TENEMOS NEGATIVOS 
(Logistica_Raw['costo_envio'] < 0).sum()

np.int64(0)

In [58]:
# TE MUESTRA LA QUE FILA TIENE EL NEGATIVO
(Logistica_Raw[Logistica_Raw['costo_envio']< 0])

Empty DataFrame
Columns: [id_pedido, id_almacen, fecha_entrega_real, estado_envio, costo_envio]
Index: []

In [ ]:
# PARA SABER MA MEDIANA, PORCENTAJE, MAXIMO,MIN,ETC...
Logistica_Raw['costo_envio'].describe()

count       88.000000
mean       928.022727
std       2885.255980
min         12.000000
25%         18.000000
50%         22.000000
75%         26.000000
max      10000.000000
Name: costo_envio, dtype: float64

In [ ]:
# PARA SABER LA FILA DE QUE COSTO_ENVIO TIENE PRECIO MUY ELEVADO
Logistica_Raw[Logistica_Raw['costo_envio'] > 100]

    id_pedido  id_almacen fecha_entrega_real estado_envio  costo_envio
6           7           1                NaN    Pendiente        10000
18         19           1         2025-06-23    Entregado        10000
27         28           4         2025-05-13    Entregado        10000
57         58           4         2026-02-08    Entregado        10000
65         66           3         2026-08-24    Entregado        10000
70         71           4                NaN    Pendiente        10000
72         73           5         2026-10-20    Entregado        10000
80          5           1         2025-02-13    Entregado        10000

In [ ]:
# VEO LA CANTIDAD DE NULL QUE HAY EN ESTADO_ENVIO
nulos = Logistica_Raw[Logistica_Raw['fecha_entrega_real'].isnull()]
nulos['estado_envio'].value_counts()

estado_envio
En tránsito    8
Pendiente      7
Cancelado      6
Retrasado      4
Name: count, dtype: int64